spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      enable-auto-commit: false
      group-id: myGroup
      auto-offset-reset: earliest
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  create:
    topics:
      enable: true
kafka:
  topic:
    signal-producer: input
    distance-producer: output